import pygame

WINDOW_SIZE = WIDTH, HEIGHT = 640, 512
LEVELS_DIR = 'level_maps'
TILE_SIZES = {'close': 64, 'further': 32}
SPRITES_INCREASE = 2
DATA_DIR = 'data'
SPRITES_SKIN_DIR = 'sprites'
SOUNDS_DIR = 'sounds'
ICONS_DIR = 'icons'
BACKGROUNDS_DIR = 'other'
GAMEOVER_FILENAME = f"{BACKGROUNDS_DIR}/gameover.jpg"
WIN_FILENAME = f"{BACKGROUNDS_DIR}/you_win.jpg"
PAUSE_FILENAME = f"{BACKGROUNDS_DIR}/pause_word.png"
INFO_ABOUT_LEVELS_FILE_NAME = 'LevelsInformation.json'
sound_play = True
SMALL_SIZE = 40
GRAVITY = 0.3
PRICE_SKINS = 5
SCREEN_RECT = (0, 0, WIDTH, HEIGHT)
ANIMATION_EVENTTYPE = pygame.USEREVENT + 1
FIRINGBULLET_EVENTTYPE = pygame.USEREVENT + 2
COIN_EVENTTYPE = pygame.USEREVENT + 3
FPS = 60
COLOR_INACTIVE = (100, 80, 255)
COLOR_ACTIVE = (100, 200, 255)
COLOR_LIST_INACTIVE = (255, 100, 100)
COLOR_LIST_ACTIVE = (255, 150, 150)
COLOR_MAIN = (255, 60, 0)
COLOR_OPTIONAL = (255, 200, 0)
LEVELS_NAMES = ["UndergrounD", "DinosauR", "TurtlE"]
INDEX_MAIN_LOOK = (0, 1)
ROW_QUANTITY_SKINS = 4
COLUMN_QUANTITY_SKINS = 2
EXIT_MESSAGE = 'exit button is pressed :)'
